// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyzsgcwjrfjudiopdnam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95enNnY3dqcmZqdWRpb3BkbmFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjU2NTUsImV4cCI6MjA2ODM0MTY1NX0.O8W4ic8594QbZ1jyzMcFjd920ezaAq8D9LAa0Znld70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);